In [3]:
import torch

# Create a sample 2D tensor
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6]])
               
# Define indices to gather elements along dimension 1 (columns)
# For each row, gather the element at the specified column index.
indices = torch.tensor([[2, 0, 1],
                        [0, 2, 1]])

result = torch.gather(input_tensor, dim=-1, index=indices)

print("Input Tensor:")
print(input_tensor)
print("\nIndices Tensor:")
print(indices)
print("\nResult from torch.gather:")
print(result)

Input Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Indices Tensor:
tensor([[2, 0, 1],
        [0, 2, 1]])

Result from torch.gather:
tensor([[3, 1, 2],
        [4, 6, 5]])
