In [2]:
import torch

B = 2
T = 3
C = 4
n_ctx = 2

input_ids = torch.arange(B * T * C, dtype=torch.float).view(B, T, C)[0]
print(input_ids.shape)
print(input_ids)
print(input_ids[None].shape)
print(input_ids[None])
print(input_ids[None, -n_ctx:].shape)
print(input_ids[None, -n_ctx:])
logits = input_ids[None, -n_ctx:]
logits = logits[0, -1]
print(logits)

torch.Size([3, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([1, 3, 4])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])
torch.Size([1, 2, 4])
tensor([[[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])
tensor([ 8.,  9., 10., 11.])


In [3]:
x = torch.tensor([0, 1] * 9)
print(x)
print(x.sort())
print(x.sort(stable=True))

tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
torch.return_types.sort(
values=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([ 2, 16,  4,  6, 14,  8,  0, 10, 12,  9, 17, 15, 13, 11,  7,  5,  3,  1]))
torch.return_types.sort(
values=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16,  1,  3,  5,  7,  9, 11, 13, 15, 17]))


In [4]:
cumul_probs = torch.tensor([0.4, 0.3, 0.2, 0.1]).cumsum(-1)
n_keep = torch.searchsorted(cumul_probs, 0.70, side="left").item() + 1

print(cumul_probs)
print(n_keep)

tensor([0.4000, 0.7000, 0.9000, 1.0000])
2


In [5]:
B = 2
T = 3
C = 4
n_ctx = 2

input_ids = torch.arange(B * T * C, dtype=torch.float).view(B, T, C)

print(input_ids.shape)
print(input_ids[:, -1].shape)

torch.Size([2, 3, 4])
torch.Size([2, 4])


In [6]:
print(input_ids.shape)
print(input_ids)
print(input_ids.flatten(0,1).shape)
print(input_ids.flatten(0,1))

torch.Size([2, 3, 4])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
torch.Size([6, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]])


In [7]:
torch.nonzero(torch.tensor([False, False, True, False]))

tensor([[2]])

In [8]:
torch.tensor([1, 2, 3]).repeat(3, 1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [9]:
torch.tensor([1, 2, 3]).unsqueeze(-1).shape

torch.Size([3, 1])

In [10]:
torch.concat([torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])], dim=0)

tensor([1, 2, 3, 4, 5, 6])

In [11]:
0 is not None

<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/tmp/ipykernel_13250/1007723362.py:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  0 is not None


True

In [12]:
torch.tensor([1,2,3,4])[:-1]

tensor([1, 2, 3])

In [13]:
ngrams_are_repeated = torch.tensor([[True, False],
                                    [False, False]]).all(-1)
ngrams = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
ngram_end_tokens = ngrams[:, [-1]]  # (batch, 1)
print(ngrams_are_repeated)
print(ngrams)
print(ngram_end_tokens)

tensor([False, False])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3],
        [6]])


In [14]:
x = torch.tensor([-1, 0, 1, 2])
torch.where(x > 0, 1.0, 0.0)

tensor([0., 0., 1., 1.])

In [15]:
no_repeat_ngram_size = 3
k = 3

tokens = torch.tensor([[8, 9, 2, 3, 4, 5, 6, 7, 8, 9], # prevent the repetition of entire n-grams [8, 9, 2]
                       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],])
batch, seq_len = tokens.shape

logprobs = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
                         [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
                         [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],])

last_ngram_prefix = tokens[:, seq_len - (no_repeat_ngram_size - 1):]
i = 0 # change here to see the effect
ngrams = tokens[:, i : i + no_repeat_ngram_size]
ngrams_are_repeated = (ngrams[:, :-1] == last_ngram_prefix).all(-1)
ngram_end_tokens = ngrams[:, [-1]]
logprobs[range(batch), ngram_end_tokens] = torch.where(ngrams_are_repeated, -1.0e4, logprobs[range(batch), ngram_end_tokens])
topk_logprobs, topk_tokenIDs = logprobs.topk(k=k, dim=-1)
print(f"batch\n{batch}")
print(f"seq_len\n{seq_len}")
print(f"tokens\n{tokens}")
print(f"last_ngram_prefix\n{last_ngram_prefix}")
print(f"ngrams\n{ngrams}")
print(f"ngrams_are_repeated\n{ngrams_are_repeated}")
print(f"ngram_end_tokens\n{ngram_end_tokens}")
print(f"logprobs\n{logprobs}")
print(f"topk_logprobs\n{topk_logprobs}")
print(f"topk_tokenIDs\n{topk_tokenIDs}")

batch
3
seq_len
10
tokens
tensor([[8, 9, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
last_ngram_prefix
tensor([[8, 9],
        [8, 9],
        [8, 9]])
ngrams
tensor([[8, 9, 2],
        [0, 1, 2],
        [0, 1, 2]])
ngrams_are_repeated
tensor([ True, False, False])
ngram_end_tokens
tensor([[2],
        [2],
        [2]])
logprobs
tensor([[ 1.0000e-01,  2.0000e-01, -1.0000e+04,  4.0000e-01,  5.0000e-01,
          6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,  1.0000e+00],
        [ 1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,  5.0000e-01,
          6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,  1.0000e+00],
        [ 1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,  5.0000e-01,
          6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,  1.0000e+00]])
topk_logprobs
tensor([[1.0000, 0.9000, 0.8000],
        [1.0000, 0.9000, 0.8000],
        [1.0000, 0.9000, 0.8000]])
topk_tokenIDs
tensor([[9, 8, 7],
       

In [16]:
import einops

logprob_sums = torch.tensor([0.1, 0.2, 0.3])

new_logprob_sums = einops.repeat(logprob_sums, 'b -> b k', k=k) + topk_logprobs # b k
print(einops.repeat(logprob_sums, 'b -> b k', k=k))
print(f"new_logprob_sums\n{new_logprob_sums}")

tensor([[0.1000, 0.1000, 0.1000],
        [0.2000, 0.2000, 0.2000],
        [0.3000, 0.3000, 0.3000]])
new_logprob_sums
tensor([[1.1000, 1.0000, 0.9000],
        [1.2000, 1.1000, 1.0000],
        [1.3000, 1.2000, 1.1000]])


In [19]:
print(f"tokens\n{tokens}")
print(f"repeat\n{einops.repeat(tokens, 'b s -> b k s', k=k)}")
print(f"unsqueeze\n{topk_tokenIDs.unsqueeze(-1)}")
new_tokens = torch.concat([einops.repeat(tokens, "b s -> b k s", k=k), topk_tokenIDs.unsqueeze(-1)], dim=-1) # b k s
new_tokens_out = new_tokens.flatten(0,1) # b*k s
new_logprob_sums_out = new_logprob_sums.flatten() # b*k
print(f"new_tokens\n{new_tokens}")
print(f"new_tokens_out\n{new_tokens_out}")
print(f"new_logprob_sums_out\n{new_logprob_sums_out}")

tokens
tensor([[8, 9, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
repeat
tensor([[[8, 9, 2, 3, 4, 5, 6, 7, 8, 9],
         [8, 9, 2, 3, 4, 5, 6, 7, 8, 9],
         [8, 9, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
unsqueeze
tensor([[[9],
         [8],
         [7]],

        [[9],
         [8],
         [7]],

        [[9],
         [8],
         [7]]])
new_tokens
tensor([[[8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 9],
         [8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 8],
         [8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 7]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 8],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 7]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9],
         [0, 1, 2, 3, 4, 

In [34]:
import torch

batch = 2
n_heads = 3
query_pos = 4 # change me
key_pos = 4

attn_scores = torch.arange(batch * n_heads * query_pos * key_pos).view(batch, n_heads, query_pos, key_pos)
print(f"attn_scores\n{attn_scores}")
print(f"attn_scores.shape[-2:]\n{attn_scores.shape[-2:]}")

attn_scores
tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]],

         [[16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31]],

         [[32, 33, 34, 35],
          [36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]],


        [[[48, 49, 50, 51],
          [52, 53, 54, 55],
          [56, 57, 58, 59],
          [60, 61, 62, 63]],

         [[64, 65, 66, 67],
          [68, 69, 70, 71],
          [72, 73, 74, 75],
          [76, 77, 78, 79]],

         [[80, 81, 82, 83],
          [84, 85, 86, 87],
          [88, 89, 90, 91],
          [92, 93, 94, 95]]]])
attn_scores.shape[-2:]
torch.Size([4, 4])


In [35]:
attn_scores.new_tensor(range(key_pos - query_pos, key_pos))

tensor([0, 1, 2, 3])

In [36]:
import einops

q_posn = einops.repeat(attn_scores.new_tensor(range(key_pos - query_pos, key_pos)),
                      "q -> q k",
                       k=key_pos)
k_posn = einops.repeat(attn_scores.new_tensor(range(key_pos)), "k -> q k", q=query_pos)
mask = q_posn < k_posn
attn_scores = attn_scores.masked_fill(mask, 1e-5)
print(f"q_posn\n{q_posn}")
print(f"k_posn\n{k_posn}")
print(f"mask\n{mask}")
print(f"attn_scores\n{attn_scores}")

q_posn
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
k_posn
tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])
mask
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])
attn_scores
tensor([[[[ 0,  0,  0,  0],
          [ 4,  5,  0,  0],
          [ 8,  9, 10,  0],
          [12, 13, 14, 15]],

         [[16,  0,  0,  0],
          [20, 21,  0,  0],
          [24, 25, 26,  0],
          [28, 29, 30, 31]],

         [[32,  0,  0,  0],
          [36, 37,  0,  0],
          [40, 41, 42,  0],
          [44, 45, 46, 47]]],


        [[[48,  0,  0,  0],
          [52, 53,  0,  0],
          [56, 57, 58,  0],
          [60, 61, 62, 63]],

         [[64,  0,  0,  0],
          [68, 69,  0,  0],
          [72, 73, 74,  0],
          [76, 77, 78, 79]],

         [[80,  0,  0,  0],
          [84, 85,  0,  0],
          

In [40]:
torch.stack([torch.tensor([0,1]),
             torch.tensor([2,3])])

tensor([[0, 1],
        [2, 3]])

In [ ]:
import torch
import einops

row = 2
d_model = 3

q = torch.arange(row * d_model).view(row, d_model)
k = torch.arange(row * d_model).view(row, d_model)
v = torch.arange(row * d_model).view(row, d_model)

qk = einops.einsum(q, k, "rq c, rk c -> rq rk")
qkv = einops.einsum(qk, v, "rq rk, rk cv -> rq cv")
print(f"qk\n{qk}")
print(f"qkv\n{qkv}")

qk
tensor([[ 5, 14],
        [14, 50]])
qkv
tensor([[ 42,  61,  80],
        [150, 214, 278]])


In [ ]:
import torch
import einops

row = 3
d_model = 3

q = torch.arange(row * d_model).view(row, d_model)
k = torch.arange(row * d_model).view(row, d_model)
v = torch.arange(row * d_model).view(row, d_model)

qk = einops.einsum(q, k, "rq c, rk c -> rq rk")
qkv = einops.einsum(qk, v, "rq rk, rk cv -> rq cv")
print(f"qk\n{qk}")
print(f"qkv\n{qkv}")

qk
tensor([[  5,  14,  23],
        [ 14,  50,  86],
        [ 23,  86, 149]])
qkv
tensor([[ 180,  222,  264],
        [ 666,  816,  966],
        [1152, 1410, 1668]])


In [ ]:
import torch
import einops

n_ctx = 10
row = 2
d_model = 3

res = torch.arange(6, 9, dtype=torch.float)

q = res
k = torch.zeros(n_ctx, d_model) # buffer
v = torch.zeros(n_ctx, d_model) # buffer

k[:row] = torch.arange(row * d_model, dtype=torch.float).view(row, d_model)
k[row+1] = res
v[:row] = torch.arange(row * d_model, dtype=torch.float).view(row, d_model)
v[row+1] = res

qk = einops.einsum(q, k, "c, rk c -> rk")
qkv = einops.einsum(qk, v, "rk, rk cv -> cv")
print(f"q\n{q}")
print(f"k\n{k}")
print(f"qk\n{qk}")
print(f"qkv\n{qkv}")

q
tensor([6., 7., 8.])
k
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [0., 0., 0.],
        [6., 7., 8.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
qk
tensor([ 23.,  86.,   0., 149.,   0.,   0.,   0.,   0.,   0.,   0.])
qkv
tensor([1152., 1410., 1668.])


In [51]:
k, v = torch.tensor([[1],
                     [2]])
print(k)
print(v)

tensor([1])
tensor([2])


In [52]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

for idx, (item1, item2) in enumerate(zip(list1, list2)):
  print(idx, item1, item2)

0 1 a
1 2 b
2 3 c
