In [2]:
import torch

# Batch matrix multiplication
a = torch.arange(start=1, end=121, step=1).reshape(2,3,4,5) # 2x3x4x5
b = torch.arange(start=1, end=121, step=1).reshape(2,3,5,4) # 2x3x5x4
torch.matmul(a,b).shape # 2x3x4x4

torch.Size([2, 3, 4, 4])

In [41]:
a = torch.arange(start=1, end=13, step=1).reshape(1,2,2,3) # 1x2x2x3 N, i, W, C
b = torch.arange(start=1, end=19, step=1).reshape(1,3,2,3) # 1x3x2x3 N, j, W, C
print("a")
print(a)
print("b")
print(b)
einsum = torch.einsum("niwc,njwc->nwic", a, b) # 1x2x2x3 N, W, b, h_2 (sum over j)
M = torch.empty((1,2,2,3))
for n in range(1):
  for w in range(2):
    for i in range(2):
      for c in range(3):
        for j in range(3):
          M[n,w,i,c] += a[n,i,w,c] * b[n,j,w,c]
print(einsum)
print(M)

a
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]])
b
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]]]])
tensor([[[[ 21,  48,  81],
          [147, 192, 243]],

         [[120, 165, 216],
          [300, 363, 432]]]])
tensor([[[[ 21.,  48.,  81.],
          [147., 192., 243.]],

         [[120., 165., 216.],
          [300., 363., 432.]]]])


# Convolution

In [ ]:
a = torch.arange(start=1, end=25, step=1).reshape(2,2,2,3) # N, H, W, C
b = torch.arange(start=1, end=25, step=1).reshape(2,2,2,3) # N, H, W, C
print("a")
print(a)
print("b")
print(b)
einsum = torch.einsum("nhwc,nhwc->nhw", a, b) # N, H, W, C
M = torch.empty((2,2,2))
for n in range(2):
  for h in range(2):
    for w in range(2):
      for c in range(3):
        M[n,h,w] += a[n,h,w,c] * b[n,h,w,c]
print("einsum")
print(einsum.shape)
print(einsum)
print("M")
print(M.shape)
print(M)

a
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])
b
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])
einsum
torch.Size([2, 2, 2])
tensor([[[  14,   77],
         [ 194,  365]],

        [[ 590,  869],
         [1202, 1589]]])
M
torch.Size([2, 2, 2])
tensor([[[  14.,   77.],
         [ 194.,  365.]],

        [[ 590.,  869.],
         [1202., 1589.]]])


In [ ]:
# nhwc,nhwc->nhw # sum over C
a = torch.arange(start=1, end=25, step=1).reshape(2,2,2,3) # N, H, W, C
b = torch.arange(start=1, end=25, step=1).reshape(2,2,2,3) # N, H, W, C
M = torch.empty((2,2,2))
n = 0
h = 0
w = 0
for c in range(3):
  M[n, h, w] += a[n,h,w,c] * b[n,h,w,c]
print(M)

tensor([[[14.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.]]])


# Transformer architecture

In [ ]:
a = torch.arange(start=1, end=37, step=1).reshape(2,3,2,3) # N, query_len, heads, head_dim
b = torch.arange(start=1, end=49, step=1).reshape(2,4,2,3) # N, key_len, heads, head_dim
print("a")
print(a)
print("b")
print(b)
einsum = torch.einsum("nqhd,nkhd->nhqk", a, b) # 2x2x3x4 N, heads, query_len, key_len
M = torch.empty((2,2,3,4))
for n in range(2):
  for h in range(2):
    for q in range(3):
      for k in range(4):
        for d in range(3):
          M[n,h,q,k] += a[n,q,h,d] * b[n,k,h,d]
print("einsum")
print(einsum.shape)
print(einsum)
print("M")
print(M.shape)
print(M)

a
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]]],


        [[[19, 20, 21],
          [22, 23, 24]],

         [[25, 26, 27],
          [28, 29, 30]],

         [[31, 32, 33],
          [34, 35, 36]]]])
b
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]],


        [[[25, 26, 27],
          [28, 29, 30]],

         [[31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42]],

         [[43, 44, 45],
          [46, 47, 48]]]])
einsum
torch.Size([2, 2, 3, 4])
tensor([[[[  14,   50,   86,  122],
          [  50,  194,  338,  482],
          [  86,  338,  590,  842]],

         [[  77,  167,  257,  347],
          [ 167,  365,  563,  761],
          [ 257,  563,  869, 1175]]],


        [[[1562, 1922, 2282, 2642],


In [ ]:
a = torch.arange(start=1, end=37, step=1).reshape(2,3,2,3) # N, query_len, heads, head_dim
b = torch.arange(start=1, end=49, step=1).reshape(2,4,2,3) # N, key_len, heads, head_dim
M = torch.empty((2,2,3,4))
n = 0
h = 0
q = 0
k = 2
for d in range(3):
  M[n,h,q,k] += a[n,q,h,d] * b[n,k,h,d]
print("M")
print(M.shape)
print(M)

M
torch.Size([2, 2, 3, 4])
tensor([[[[ 0.,  0., 86.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]]])


In [26]:
print(a)
n = 0
q = 0
print(a[n,q,:,:]) # n,q,h,d

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]]],


        [[[19, 20, 21],
          [22, 23, 24]],

         [[25, 26, 27],
          [28, 29, 30]],

         [[31, 32, 33],
          [34, 35, 36]]]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [25]:
print(b)
n = 0
k = 2
print(b[n,k,:,:]) # n,k,h,d

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]],

         [[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]],


        [[[25, 26, 27],
          [28, 29, 30]],

         [[31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42]],

         [[43, 44, 45],
          [46, 47, 48]]]])
tensor([[13, 14, 15],
        [16, 17, 18]])


# Transformer

In [33]:
# key_len and value_len are the same
# attention shape: (N, heads, query_len, key_len)
# values shape: (N, value_len, heads, head_dim)
# out shape: (N, query_len, heads, head_dim)
attention = torch.arange(start=1, end=49, step=1).reshape(2,3,2,4) # N, heads, query_len, key_len
values = torch.arange(start=1, end=73, step=1).reshape(2,4,3,3) # N, value_len, heads, head_dim
print("attention")
print(attention)
print("values")
print(values)
einsum = torch.einsum("nhql,nlhd->nqhd", attention, values) # N, query_len, heads, head_dim
M = torch.empty((2,2,3,3))
for n in range(2):
  for q in range(2):
    for h in range(3):
      for d in range(3):
        for l in range(4):
          M[n,q,h,d] += attention[n,h,q,l] * values[n,l,h,d]
print("einsum")
print(einsum.shape)
print(einsum)
print("M")
print(M.shape)
print(M)

attention
tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],

         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[25, 26, 27, 28],
          [29, 30, 31, 32]],

         [[33, 34, 35, 36],
          [37, 38, 39, 40]],

         [[41, 42, 43, 44],
          [45, 46, 47, 48]]]])
values
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],

         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]]],


        [[[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]],

         [[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],

         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]]]])
einsum
torch.Size([2, 2, 3, 3])
tenso

In [36]:
# key_len and value_len are the same
# attention shape: (N, heads, query_len, key_len)
# values shape: (N, value_len, heads, head_dim)
# out shape: (N, query_len, heads, head_dim)
attention = torch.arange(start=1, end=49, step=1).reshape(2,3,2,4) # N, heads, query_len, key_len
values = torch.arange(start=1, end=73, step=1).reshape(2,4,3,3) # N, value_len, heads, head_dim
M = torch.empty((2,2,3,3))
n = 0
q = 0
h = 0
d = 0
for l in range(4):
  M[n,q,h,d] += attention[n,h,q,l] * values[n,l,h,d]
print("M")
print(M.shape)
print(M)

M
torch.Size([2, 2, 3, 3])
tensor([[[[190.,   0.,   0.],
          [  0.,   0.,   0.],
          [  0.,   0.,   0.]],

         [[  0.,   0.,   0.],
          [  0.,   0.,   0.],
          [  0.,   0.,   0.]]],


        [[[  0.,   0.,   0.],
          [  0.,   0.,   0.],
          [  0.,   0.,   0.]],

         [[  0.,   0.,   0.],
          [  0.,   0.,   0.],
          [  0.,   0.,   0.]]]])


In [50]:
print(attention)
n = 0
h = 0
print(attention[n,h,:,:]) # n,h,q,l

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],

         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[25, 26, 27, 28],
          [29, 30, 31, 32]],

         [[33, 34, 35, 36],
          [37, 38, 39, 40]],

         [[41, 42, 43, 44],
          [45, 46, 47, 48]]]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [47]:
print(values)
n = 0
l = 0
print(values[n,l,:,:]) # n,l,h,d

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],

         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]]],


        [[[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]],

         [[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],

         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [53]:
print(1 * 1 + 2 * 10 + 3 * 19 + 4 * 28)

190
