In [27]:
import torch

a = torch.arange(0, 10, step=1)
print("a")
print(a)
print("a.expand(3, 10)")
print(a.expand(3, 10))

a
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a.expand(3, 10)
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [22]:
a = torch.arange(0, 10, step=1).reshape(2, 5)
print(a.shape)
print(a)
a = a.unsqueeze(1)
print(a.shape)
print(a)
a = a.unsqueeze(2)
print(a.shape)
print(a)

torch.Size([2, 5])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.Size([2, 1, 5])
tensor([[[0, 1, 2, 3, 4]],

        [[5, 6, 7, 8, 9]]])
torch.Size([2, 1, 1, 5])
tensor([[[[0, 1, 2, 3, 4]]],


        [[[5, 6, 7, 8, 9]]]])


In [32]:
a = torch.tril(torch.ones(3, 3))
print(a)
print(a.shape)
a = a.expand(2, 1, 3, 3)
print(a)
print(a.shape)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
torch.Size([3, 3])
tensor([[[[1., 0., 0.],
          [1., 1., 0.],
          [1., 1., 1.]]],


        [[[1., 0., 0.],
          [1., 1., 0.],
          [1., 1., 1.]]]])
torch.Size([2, 1, 3, 3])
