In [18]:
import torch

z = torch.zeros(3,2)
print(z)
y = z.t()
# tensor y is not stored in a contiguous block of memory.
print(y)
print(y.size())
y.view(6)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [25]:
import torch

x = torch.zeros(3, 2)
linear = torch.nn.Linear(2, 2)
y = linear(x)
print(y)
print(y.size())
y.view(6)

tensor([[-0.5053, -0.3817],
        [-0.5053, -0.3817],
        [-0.5053, -0.3817]], grad_fn=<AddmmBackward0>)
torch.Size([3, 2])


tensor([-0.5053, -0.3817, -0.5053, -0.3817, -0.5053, -0.3817],
       grad_fn=<ViewBackward0>)