```
x = tensor([[x00, x01],   ──────────┐
            [x10, x11],             │
            [x20, x21]])            │
                                    │
                                    ▼
linear = nn.Linear(2,1)      ┌──────────────┐
                             │ W = [w1, w2] │  (weights shape: [1,2])
                             │ b = [b]      │  (bias shape: [1])
                             └──────────────┘
                                    │
                                    ▼
y = linear(x)              ┌──────────────────────────┐
                           │ y0 = x00*w1 + x01*w2 + b │
                           │ y1 = x10*w1 + x11*w2 + b │
                           │ y2 = x20*w1 + x21*w2 + b │
                           └──────────────────────────┘
                                    │
                                    ▼
                           tensor([[y0],    (shape [3,1])
                                   [y1],
                                   [y2]])         
```

```
x = tensor([[x00, x01],   ──────────┐
            [x10, x11],             │
            [x20, x21]])            │
                                    │
                                    ▼
linear = nn.Linear(2,2)      ┌───────────────────┐
                             │ W = [[w11, w12],  │  (weights shape: [2,2])
                             │      [w21, w22]]  │  
                             │ b = [b1, b2]      │  (bias shape: [2])
                             └───────────────────┘
                                    │
                                    ▼
y = linear(x)          ┌───────────────────────────────────┐
                       │ y00 = x00*w11 + x01*w21 + b1 = b1 │
                       │ y01 = x00*w12 + x01*w22 + b2 = b2 │
                       │ y10 = x10*w11 + x11*w21 + b1 = b1 │
                       │ y11 = x10*w12 + x11*w22 + b2 = b2 │
                       │ y20 = x20*w11 + x21*w21 + b1 = b1 │
                       │ y21 = x20*w12 + x21*w22 + b2 = b2 │
                       └───────────────────────────────────┘
                                    │
                                    ▼
                           tensor([[y00, y01],    (shape [3,2])
                                   [y10, y11],
                                   [y20, y21]])
```

In [ ]:
import torch

N = 3
query_length = 2
embed_size = 2
heads = 2
head_dim = embed_size // heads
assert head_dim * heads == embed_size, "embed_size must be divisible by heads"
print(f"head_dim: {head_dim}")

x = torch.zeros(N,query_length)
print(f"x:\n{x}")
linear = torch.nn.Linear(embed_size,embed_size)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y_heads = y.view(N, heads, head_dim)
print(f"y_heads:\n{y_heads}")

head_dim: 1
x:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
y:
tensor([[ 0.2404, -0.0870],
        [ 0.2404, -0.0870],
        [ 0.2404, -0.0870]], grad_fn=<AddmmBackward0>)
w:
Parameter containing:
tensor([[-0.0445,  0.2860],
        [-0.2840, -0.1913]], requires_grad=True)
b:
Parameter containing:
tensor([ 0.2404, -0.0870], requires_grad=True)
y_heads:
tensor([[[ 0.2404],
         [-0.0870]],

        [[ 0.2404],
         [-0.0870]],

        [[ 0.2404],
         [-0.0870]]], grad_fn=<ViewBackward0>)
