```
x = tensor([[x00, x01],   ──────────┐
            [x10, x11],             │
            [x20, x21]])            │
                                    │
                                    ▼
linear = nn.Linear(2,1)      ┌──────────────┐
                             │ W = [w1, w2] │  (weights shape: [1,2])
                             │ b = [b]      │  (bias shape: [1])
                             └──────────────┘
                                    │
                                    ▼
y = linear(x)              ┌──────────────────────────┐
                           │ y0 = x00*w1 + x01*w2 + b │
                           │ y1 = x10*w1 + x11*w2 + b │
                           │ y2 = x20*w1 + x21*w2 + b │
                           └──────────────────────────┘
                                    │
                                    ▼
                           tensor([[y0],    (shape [3,1])
                                   [y1],
                                   [y2]])         
```

In [38]:
import torch
import torch.nn as nn

x = torch.zeros(3,2)

linear = nn.Linear(2,1)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y:
tensor([[0.6669],
        [0.6669],
        [0.6669]], grad_fn=<AddmmBackward0>)
w:
Parameter containing:
tensor([[-0.1039,  0.6855]], requires_grad=True)
b:
Parameter containing:
tensor([0.6669], requires_grad=True)


```
x = tensor([[[x000, x001],   ──────────┐
             [x010, x011]],            │
                                       │
            [[x100, x101],             │
             [x110, x111]],            │
                                       │
            [[x200, x201],             │
             [x210, x211]]])           │
                                       │
                                       ▼
linear = nn.Linear(2,1)         ┌──────────────┐
                                │ W = [w1, w2] │  (weights shape: [1,2])
                                │ b = [b]      │  (bias shape: [1])
                                └──────────────┘
                                       │
                                       ▼
y = linear(x)                 ┌───────────────────────────┐
                              │ y00 = x000*w1 + x001*w2 + b │
                              │ y01 = x010*w1 + x011*w2 + b │
                              │                             │
                              │ y10 = x100*w1 + x101*w2 + b │
                              │ y11 = x110*w1 + x111*w2 + b │
                              │                             │
                              │ y20 = x200*w1 + x201*w2 + b │
                              │ y21 = x210*w1 + x211*w2 + b │
                              └───────────────────────────┘
                                       │
                                       ▼
                              tensor([[[y00],     (shape [3,2,1])
                                       [y01]],
                                       
                                      [[y10],
                                       [y11]],
                                       
                                      [[y20],
                                       [y21]]])
```

In [39]:
import torch
import torch.nn as nn

x = torch.zeros(3,2,2)

linear = nn.Linear(2,1)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y:
tensor([[[0.6119],
         [0.6119]],

        [[0.6119],
         [0.6119]],

        [[0.6119],
         [0.6119]]], grad_fn=<ViewBackward0>)
w:
Parameter containing:
tensor([[-0.2142, -0.6138]], requires_grad=True)
b:
Parameter containing:
tensor([0.6119], requires_grad=True)


```
x = tensor([[x00, x01],   ──────────┐
            [x10, x11],             │
            [x20, x21]])            │
                                    │
                                    ▼
linear = nn.Linear(2,2)      ┌───────────────────┐
                             │ W = [[w11, w12],  │  (weights shape: [2,2])
                             │      [w21, w22]]  │  
                             │ b = [b1, b2]      │  (bias shape: [2])
                             └───────────────────┘
                                    │
                                    ▼
y = linear(x)          ┌───────────────────────────────────┐
                       │ y00 = x00*w11 + x01*w21 + b1 = b1 │
                       │ y01 = x00*w12 + x01*w22 + b2 = b2 │
                       │ y10 = x10*w11 + x11*w21 + b1 = b1 │
                       │ y11 = x10*w12 + x11*w22 + b2 = b2 │
                       │ y20 = x20*w11 + x21*w21 + b1 = b1 │
                       │ y21 = x20*w12 + x21*w22 + b2 = b2 │
                       └───────────────────────────────────┘
                                    │
                                    ▼
                           tensor([[y00, y01],    (shape [3,2])
                                   [y10, y11],
                                   [y20, y21]])
```

In [37]:
import torch
import torch.nn as nn

x = torch.zeros(3,2)

linear = nn.Linear(2,2)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y:
tensor([[-0.1297,  0.0891],
        [-0.1297,  0.0891],
        [-0.1297,  0.0891]], grad_fn=<AddmmBackward0>)
w:
Parameter containing:
tensor([[ 0.4018,  0.4053],
        [ 0.4382, -0.1442]], requires_grad=True)
b:
Parameter containing:
tensor([-0.1297,  0.0891], requires_grad=True)


```
x = tensor([[[x000, x001],   ──────────┐
             [x010, x011]],            │
                                       │
            [[x100, x101],             │
             [x110, x111]],            │
                                       │
            [[x200, x201],             │
             [x210, x211]]])           │
                                       │
                                       ▼
linear = nn.Linear(2,2)         ┌────────────────────┐
                                │ W = [[w11, w12],   │  (weights shape: [2,2])
                                │      [w21, w22]]   │
                                │ b = [b1, b2]       │  (bias shape: [2])
                                └────────────────────┘
                                       │
                                       ▼
y = linear(x)                 ┌─────────────────────────────────┐
                              │ y000 = x000*w11 + x001*w21 + b1 │
                              │ y001 = x000*w12 + x001*w22 + b2 │
                              │                                 │
                              │ y010 = x010*w11 + x011*w21 + b1 │
                              │ y011 = x010*w12 + x011*w22 + b2 │
                              │                                 │
                              │ y100 = x100*w11 + x101*w21 + b1 │
                              │ y101 = x100*w12 + x101*w22 + b2 │
                              │                                 │
                              │ y110 = x110*w11 + x111*w21 + b1 │
                              │ y111 = x110*w12 + x111*w22 + b2 │
                              │                                 │
                              │ y200 = x200*w11 + x201*w21 + b1 │
                              │ y201 = x200*w12 + x201*w22 + b2 │
                              │                                 │
                              │ y210 = x210*w11 + x211*w21 + b1 │
                              │ y211 = x210*w12 + x211*w22 + b2 │
                              └─────────────────────────────────┘
                                       │
                                       ▼
                              tensor([[[y000, y001],     (shape [3,2,2])
                                       [y010, y011]],
                                       
                                      [[y100, y101],
                                       [y110, y111]],
                                       
                                      [[y200, y201],
                                       [y210, y211]]])
```

In [40]:
import torch
import torch.nn as nn

x = torch.zeros(3,2,2)

linear = nn.Linear(2,2)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y:
tensor([[[-0.7005,  0.4835],
         [-0.7005,  0.4835]],

        [[-0.7005,  0.4835],
         [-0.7005,  0.4835]],

        [[-0.7005,  0.4835],
         [-0.7005,  0.4835]]], grad_fn=<ViewBackward0>)
w:
Parameter containing:
tensor([[-0.6787, -0.2687],
        [-0.3189, -0.6845]], requires_grad=True)
b:
Parameter containing:
tensor([-0.7005,  0.4835], requires_grad=True)


# Experiment 1

How Multi-head Attention is used in Transformer.

Note: I don't aim to be right about Multi-head Attention, I just want to do the big picture.

In [ ]:
import torch
import torch.nn as nn

N = 3
vocab_size = 4
query_len = 2
embed_size = 4
heads = 2
head_dim = embed_size // heads
assert head_dim * heads == embed_size, "embed_size must be divisible by heads"
print(f"head_dim: {head_dim}")

x = torch.zeros(N, query_len, dtype=torch.long)
print(f"x shape:\n{x.shape}")
print(f"x:\n{x}")

word_embedding = nn.Embedding(vocab_size, embed_size)
x = word_embedding(x)
print(f"x after word_embedding shape:\n{x.shape}")
print(f"x after word_embedding:\n{x}")

linear = nn.Linear(embed_size,embed_size)
y = linear(x)
print(f"y:\n{y}")
print(f"w:\n{linear.weight}")
print(f"b:\n{linear.bias}")

y_heads = y.view(N, query_len, heads, head_dim)
print(f"y_heads:\n{y_heads}")

head_dim: 2
x shape:
torch.Size([3, 2])
x:
tensor([[0, 0],
        [0, 0],
        [0, 0]])
x after word_embedding shape:
torch.Size([3, 2, 4])
x after word_embedding:
tensor([[[ 1.7977, -0.9563,  1.9430, -0.8911],
         [ 1.7977, -0.9563,  1.9430, -0.8911]],

        [[ 1.7977, -0.9563,  1.9430, -0.8911],
         [ 1.7977, -0.9563,  1.9430, -0.8911]],

        [[ 1.7977, -0.9563,  1.9430, -0.8911],
         [ 1.7977, -0.9563,  1.9430, -0.8911]]], grad_fn=<EmbeddingBackward0>)
y:
tensor([[[-0.2908,  0.4218, -0.8730,  0.0299],
         [-0.2908,  0.4218, -0.8730,  0.0299]],

        [[-0.2908,  0.4218, -0.8730,  0.0299],
         [-0.2908,  0.4218, -0.8730,  0.0299]],

        [[-0.2908,  0.4218, -0.8730,  0.0299],
         [-0.2908,  0.4218, -0.8730,  0.0299]]], grad_fn=<ViewBackward0>)
w:
Parameter containing:
tensor([[ 0.0584,  0.2450,  0.0613,  0.3792],
        [ 0.2888, -0.2241, -0.0152,  0.1809],
        [-0.0471, -0.2589, -0.3601, -0.1770],
        [-0.0260, -0.1123, -0.0081,