In [ ]:
import torch

loss = torch.nn.CrossEntropyLoss()

input = torch.tensor([1, float('-inf')])
target = torch.tensor(0)
output = loss(input, target)
print(f"input.shape: {input.shape}")
print(f"target.shape: {target.shape}")
print(f"output: {output}")

input = torch.tensor([[1, float('-inf')],
                      [float('-inf'), 1]])
target = torch.tensor([0,
                       1])
output = loss(input, target)
print(f"input.shape: {input.shape}")
print(f"target.shape: {target.shape}")
print(f"output: {output}")

input = torch.tensor([[[            1, float('-inf'), float('-inf')],
                       [float('-inf'),             1, float('-inf')]],
                      [[float('-inf'),             1, float('-inf')],
                       [            1, float('-inf'), float('-inf')]]])
# input: (N, d1, C)
input = input.transpose(1, 2)
# input: (N, C, d1)
target = torch.tensor([[0, 1],
                       [1, 0]])
output = loss(input, target)
# expected input: (N, C, d1)
# expected target: (N, d1)
print(f"input.shape: {input.shape}")
print(f"input:\n{input}")
print(f"target.shape: {target.shape}")
print(f"target:\n{target}")
print(f"output: {output}")

input.shape: torch.Size([2])
target.shape: torch.Size([])
output: 0.0
input.shape: torch.Size([2, 2])
target.shape: torch.Size([2])
output: 0.0
input.shape: torch.Size([2, 3, 2])
input:
tensor([[[1., -inf],
         [-inf, 1.],
         [-inf, -inf]],

        [[-inf, 1.],
         [1., -inf],
         [-inf, -inf]]])
target.shape: torch.Size([2, 2])
target:
tensor([[0, 1],
        [1, 0]])
output: 0.0


In [ ]:
import torch
import torch.nn.functional as F

criterion = torch.nn.CrossEntropyLoss()

output = torch.tensor([[[float('-inf'),    1, float('-inf'), float('-inf'), float('-inf')],
                        [float('-inf'), float('-inf'),    1, float('-inf'), float('-inf')],
                        [float('-inf'), float('-inf'), float('-inf'), float('-inf'),    1],
                        [float('-inf'), float('-inf'), float('-inf'),    1, float('-inf')],
                        [float('-inf'), float('-inf'), float('-inf'), float('-inf'),    1]],
                       [[float('-inf'),    1, float('-inf'), float('-inf'), float('-inf')], 
                        [   1, float('-inf'), float('-inf'), float('-inf'), float('-inf')],
                        [float('-inf'), float('-inf'), float('-inf'), float('-inf'),    1],
                        [float('-inf'), float('-inf'), float('-inf'),    1, float('-inf')],
                        [float('-inf'), float('-inf'), float('-inf'), float('-inf'),    1]]])
# output: (n, token_len, num_tokens)
labels = torch.tensor([[1, 2, 4, 3, 4],
                       [1, 0, 4, 3, 4]])
# labels: (n, token_len)
# is statquest <EOS> awesome <EOS>
# is what <EOS> awesome <EOS>

loss = criterion(output, labels)
print(f"loss: {loss}")

loss: 200000000.0


loss: 200000000.0


In [12]:
import torch

token_to_id = {'what': 0, 'is': 1, 'statquest': 2, 'awesome': 3, '<EOS>': 4}
id_to_token = dict(map(reversed, token_to_id.items()))

n = 2
q_len = 6
num_tokens = 5

output = torch.tensor([[token_to_id[token] for token in sentence.split()]
                       for sentence in ["what is statquest <EOS> awesome awesome",
                                        "what is statquest <EOS> awesome awesome"]],
                       dtype=torch.float32)
# output: (n, q_len, num_tokens)
print(f"output:\n{output}")

labels = torch.tensor([[token_to_id[token] for token in sentence.split()]
                       for sentence in ["what is statquest <EOS> awesome <EOS>",
                                        "what is statquest <EOS> awesome <EOS>"]],
                       dtype=torch.float32)
# labels: (n, q_len)
print(f"labels:\n{labels}")

criterion = torch.nn.CrossEntropyLoss()
loss = criterion(output, labels)
print(f"loss: {loss}")


output:
tensor([[0., 1., 2., 4., 3., 3.],
        [0., 1., 2., 4., 3., 3.]])
labels:
tensor([[0., 1., 2., 4., 3., 4.],
        [0., 1., 2., 4., 3., 4.]])
loss: 23.271833419799805
