In [ ]:
import torch

qk_t = torch.tensor([[[1.0,2.0,3.0],
                      [4.0,5.0,6.0],
                      [7.0,8.0,9.0]],
                     [[10.0,11.0,12.0],
                      [13.0,14.0,15.0],
                      [16.0,17.0,18.0]]])
token_len = qk_t.size(1)
mask = torch.tril(torch.ones(token_len, token_len)) == 0
qk_t = qk_t.masked_fill(mask, float('-inf'))
print(f"qk_t + M:\n{qk_t}")
qk_t = torch.softmax(qk_t, dim=-1)
print(f"qk_t:\n{qk_t}")
# The pizza came out of the oven and it tasted good!
#    the the,         -inf,        -inf,       -inf,      -inf,       -inf,        -inf,       -inf,      -inf,          -inf,        -inf
#  pizza the,  pizza pizza,        -inf,       -inf,      -inf,       -inf,        -inf,       -inf,      -inf,          -inf,        -inf
#   came the,   came pizza,   came came,       -inf,      -inf,       -inf,        -inf,       -inf,      -inf,          -inf,        -inf
#    out the,    out pizza,    out came,    out out,      -inf,       -inf,        -inf,       -inf,      -inf,          -inf,        -inf
#     of the,     of pizza,     of came,     of out,     of of,       -inf,        -inf,       -inf,      -inf,          -inf,        -inf
#    the the,    the pizza,    the came,    the out,    the of,    the the,        -inf,       -inf,      -inf,          -inf,        -inf
#   oven the,   oven pizza,   oven came,   oven out,   oven of,   oven the,   oven oven,       -inf,      -inf,          -inf,        -inf
#    and the,    and pizza,    and came,    and out,    and of,    and the,    and oven,    and and,      -inf,          -inf,        -inf
#     it the,     it pizza,     it came,     it out,     it of,     it the,     it oven,     it and,     it it,          -inf,        -inf
# tasted the, tasted pizza, tasted came, tasted out, tasted of, tasted the, tasted oven, tasted and, tasted it, tasted tasted,        -inf
#  good! the,  good! pizza,  good! came,  good! out,  good! of,  good! the,  good! oven,  good! and,  good! it,  good! tasted, good! good!

tensor([[[0.5000,   -inf,   -inf],
         [2.0000, 2.5000,   -inf],
         [3.5000, 4.0000, 4.5000]],

        [[5.0000,   -inf,   -inf],
         [6.5000, 7.0000,   -inf],
         [8.0000, 8.5000, 9.0000]]])
qk_t + M:
tensor([[[ 1., -inf, -inf],
         [ 4.,  5., -inf],
         [ 7.,  8.,  9.]],

        [[10., -inf, -inf],
         [13., 14., -inf],
         [16., 17., 18.]]])
qk_t:
tensor([[[1.0000, 0.0000, 0.0000],
         [0.2689, 0.7311, 0.0000],
         [0.0900, 0.2447, 0.6652]],

        [[1.0000, 0.0000, 0.0000],
         [0.2689, 0.7311, 0.0000],
         [0.0900, 0.2447, 0.6652]]])


In [9]:
torch.exp(torch.tensor(13)) / (torch.exp(torch.tensor(13)) + torch.exp(torch.tensor(14)))

tensor(0.2689)