In [2]:
import torch
import torch.nn as nn

# Create an input tensor with shape (batch_size, token_len, num_tokens)
# For example: batch_size = 1, token_len = 3, num_tokens = 2
input_tensor = torch.tensor([
  [[1.0,  2.0],  # token 1
   [3.0,  4.0],  # token 2
   [5.0,  6.0]], # token 3
  [[7.0,  8.0],  # token 1
   [9.0, 10.0],  # token 2
   [11.0, 12.0]] # token 3
])

# Create a Linear layer that processes the last dimension
# Here, in_features = num_tokens = 2, out_features = 2
linear = nn.Linear(2, 2, bias=True)

# Manually set weights and bias for deterministic output:
# Weight shape is (out_features, in_features).
# Let's set the weight matrix as an identity matrix and zero biases.
linear.weight.data = torch.tensor([[1.0, 2.0],  # token 1
                                   [3.0, 4.0]]) # token 2
linear.bias.data = torch.tensor([0.0, 0.0])

# Apply the Linear layer over the input tensor.
# Note: nn.Linear automatically applies the transformation over the last dimension,
# so the output shape will remain (batch_size, token_len, out_features)
output = linear(input_tensor)
print(f"input:\n{input_tensor}")
print(f"weight:\n{linear.weight}")
print(f"output:\n{output}")

# For manual calculation:
# For each token, the transformation is:
#   output[token] = input[token] * weight^T + bias
# output_manual = torch.matmul(input_tensor, linear.weight.T) + linear.bias
output_manual = input_tensor.matmul(linear.weight.T) + linear.bias
print(f"output (manual):\n{output_manual}")

input:
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])
weight:
Parameter containing:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
output:
tensor([[[ 5., 11.],
         [11., 25.],
         [17., 39.]],

        [[23., 53.],
         [29., 67.],
         [35., 81.]]], grad_fn=<ViewBackward0>)
output (manual):
tensor([[[ 5., 11.],
         [11., 25.],
         [17., 39.]],

        [[23., 53.],
         [29., 67.],
         [35., 81.]]], grad_fn=<AddBackward0>)
