In [ ]:
import torch

# Create a tensor of numbers
probs = torch.tensor([[0.05, 0.05, 0.4, 0.5],
                      [0.5,  0.4, 0.05, 0.05],
                      [0.05, 0.05, 0.5, 0.4]])

# Get the top 3 values using torch.topk
topk_values, topk_indices = torch.topk(probs, k=3, dim=-1)
ix = torch.multinomial(topk_values, 1)
xcol = torch.gather(topk_indices, dim=-1, index=ix) # (B,1)

print(f"topk_values:\n{topk_values}")
print(f"topk_indices:\n{topk_indices}")
print(f"ix:\n{ix}")
print(f"xcol:\n{xcol}")

topk_values:
tensor([[0.5000, 0.4000, 0.0500],
        [0.5000, 0.4000, 0.0500],
        [0.5000, 0.4000, 0.0500]])
topk_indices:
tensor([[3, 2, 1],
        [0, 1, 2],
        [2, 3, 0]])
ix:
tensor([[0],
        [1],
        [1]])
xcol:
tensor([[3],
        [1],
        [3]])


In [ ]:
# Let's create a simple tensor
data = torch.tensor([[10, 20, 30],
                     [40, 50, 60]])

# We define indices to pick elements from each row.
# For the first row, we pick elements at positions 0 and 2.
# For the second row, we pick elements at positions 1 and 0.
indices = torch.tensor([[0, 2],
                        [1, 0]])

# Use torch.gather to select elements along dim=1
gathered = torch.gather(data, dim=1, index=indices)

print("Data tensor:")
print(data)
print("\nIndices tensor:")
print(indices)
print("\nGathered tensor:")
print(gathered)

Data tensor:
tensor([[10, 20, 30],
        [40, 50, 60]])

Indices tensor:
tensor([[0, 2],
        [1, 0]])

Gathered tensor:
tensor([[10, 30],
        [50, 40]])
