In [19]:
import torch

import torch.nn as nn

# Define vocabulary sizes and embedding dimensions
vocab_size = 10
embedding_dim = 5

# Create a tensor of indices for lookup
indices = torch.LongTensor([2, 4, 6])

# Initialize an embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# For reproducibility, use a fixed seed and assign random weights to the embedding layer
torch.manual_seed(0)
embedding.weight.data = torch.randn(vocab_size, embedding_dim)

# Lookup using the nn.Embedding layer
emb_output = embedding(indices)

# Manual embedding: convert indices to one-hot vectors and multiply with the weight matrix
one_hot = torch.eye(vocab_size)[indices]

manual_output_matmul = one_hot @ embedding.weight.data
manual_output_indices = embedding.weight.data[indices]

print("Embedding weight:\n", embedding.weight.data)
print("Embedding lookup output:\n", emb_output)
print("One hot vectors:\n", one_hot)
print("Manual multiplication matmul output:\n", manual_output_matmul)
print("Manual multiplication indices output:\n", manual_output_indices)

Embedding weight:
 tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
        [ 0.6920, -0.3160, -2.1152,  0.3223, -1.2633],
        [ 0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
        [-0.2473, -1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
        [-0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
        [ 0.9463, -0.8437, -0.6136,  0.0316,  1.0554],
        [ 0.1778, -0.2303, -0.3918,  0.5433, -0.3952],
        [ 0.2055, -0.4503,  1.5210,  3.4105, -1.5312],
        [-1.2341,  1.8197, -0.5515, -1.3253,  0.1886]])
Embedding lookup output:
 tensor([[ 0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
        [ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
        [ 0.9463, -0.8437, -0.6136,  0.0316,  1.0554]],
       grad_fn=<EmbeddingBackward0>)
One hot vectors:
 tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])
Manual multiplication matmul out

In [ ]:
linear = torch.nn.Linear(embedding_dim, vocab_size, bias=False)
linear.weight = embedding.weight
unembed_output = linear(emb_output)
print("Unembedding output:\n", unembed_output)

Unembedding output:
 tensor([[-0.3683, -1.1207,  3.0108,  0.8809,  2.8207,  3.2548,  1.2154,  0.1754,
          2.6265, -1.3670],
        [ 1.0361,  1.2773,  2.8207,  4.1796,  6.8899,  3.6210,  2.9384,  1.3087,
          5.4752, -5.6950],
        [ 0.9426,  0.8962,  1.2154,  2.8031,  2.9384,  1.1977,  3.0985,  0.2031,
         -1.8670, -2.2076]], grad_fn=<MmBackward0>)
