In [10]:
import torch

x = torch.arange(2 * 3 * 4).reshape(2, 3, 4)
x2 = x.view(2 * 3, 4)
y = torch.randint(4, (2, 3))
y2 = y.view(2 * 3)
print(f"x:\n{x}")
print(f"x2:\n\{x2}")
print(f"x2[0]:\n{x2}")
print(f"y:\n{y}")
print(f"y:\n{y2}")

x:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
x2:
\tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
x2[0]:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
y:
tensor([[1, 2, 0],
        [3, 0, 0]])
y:
tensor([1, 2, 0, 3, 0, 0])


In [235]:
logits = torch.arange(2 * 3 * 4, dtype=torch.float32).reshape(2, 3, 4)
logits2 = logits[:, -1, :]
print(f"logits:\n{logits}")
print(f"logits2:\n{logits2}")
print(f"logits2.shape: {logits2.shape}")

logits:
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
logits2:
tensor([[ 8.,  9., 10., 11.],
        [20., 21., 22., 23.]])
logits2.shape: torch.Size([2, 4])


In [229]:
probs = torch.tensor([[0.05, 0.0, 0.0, 0.95],
                      [0.1, 0.2, 0.7, 0.0],
                      [0.2, 0.3, 0.5, 0.0]])

idx_next = torch.multinomial(probs, num_samples=1)

print(f"probs:\n{probs}")
print(f"idx_next:\n{idx_next}")

probs:
tensor([[0.0500, 0.0000, 0.0000, 0.9500],
        [0.1000, 0.2000, 0.7000, 0.0000],
        [0.2000, 0.3000, 0.5000, 0.0000]])
idx_next:
tensor([[3],
        [2],
        [2]])


In [258]:
# Create two sample tensors with the same shape
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
y = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])
print(f"x.shape: {x.shape}")
print(f"y.shape: {y.shape}")

# Stack tensors along a new dimension (default dim=0)
stacked_dim0 = torch.stack([x, y])
print("Stacked along dimension 0:")
print(stacked_dim0)
print(f"stacked_dim0.shape: {stacked_dim0.shape}")

x.shape: torch.Size([2, 3])
y.shape: torch.Size([2, 3])
Stacked along dimension 0:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
stacked_dim0.shape: torch.Size([2, 2, 3])


In [ ]:
# Create two sample 2D tensors with the same number of rows
idx = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])
idx_next = torch.tensor([[7],
                         [10]])

# Concatenate t1 and t2 along dimension 1 (columns)
concatenated_dim1 = torch.cat([idx, idx_next], dim=1)
print("Concatenated tensor along dim=1:")
print(concatenated_dim1)

Concatenated tensor along dim=1:
tensor([[ 1,  2,  3,  7],
        [ 4,  5,  6, 10]])


In [284]:
# Create two tensors that are close within a tolerance
tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([1.0, 2.00005, 2.99995])

# Check if all elements are close with absolute tolerance of 1e-4
result = torch.allclose(tensor1, tensor2, atol=1e-4)
print("Are tensor1 and tensor2 close?", result)

Are tensor1 and tensor2 close? True


In [286]:
idx = torch.arange(2 * 3).reshape(2, 3)
print(idx)
print(idx[:, -2:])

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[1, 2],
        [4, 5]])
